#################################################################
# Puppet Managed Configuration File                             #
# Do not edit this file manually as changes will be overwritten #
# by the PuppetMaster                                           #
#################################################################
# Purpose: Includes DSM bin to paths                            #
#################################################################

if [[ -d /opt/tivoli/tsm/client/ba/bin ]]; then
    export PATH=:/opt/tivoli/tsm/client/ba/bin:$PATH
fi
